kafka:
  bootstrap_servers: "localhost:9092"
  topic: "market-data"
risk:
  max_position: 10000.0
  volatility_threshold: 0.05
model:
  path: "models/trading_model.h5"
auth:
  secret_key: "your-secret-key"
prometheus:
  metrics_port: 9090